source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
inhibit_all_warnings!

workspace 'ZVProgressHUDDemo.xcworkspace'

target 'ZVProgressHUDDemo' do
	project 'ZVProgressHUDDemo.xcodeproj'
	use_frameworks! :linkage => :static
 	pod 'SVProgressHUD', '~> 2.2.5'

end

target 'ZVProgressHUD' do
	project '../ZVProgressHUD/ZVProgressHUD.xcodeproj'
	use_frameworks! :linkage => :dynamic

	pod 'SVProgressHUD', '~> 2.2.5'

end
